resilience4j.circuitbreaker:
  instances:
    carService:
      registerHealthIndicator: true
      slidingWindowSize: 5
      minimumNumberOfCalls: 2
      permittedNumberOfCallsInHalfOpenState: 3
      waitDurationInOpenState: 10000
      failureRateThreshold: 50
